### PR TITLE
some adjustments

### PR DESCRIPTION
**Pull request by ente76**
Correction on systemd::journal::Journal.open_files(). The API offers flags which I initially implemented in Rust as well. But the documentation clearly states, that these flags are ignored. Since that is not temporarily but (due to technical limitations) permanently, I adjusted the Rust implementation to skip the flags (its just confusing!). The documentation was incorrect as well. I fixed that too.

Correction on systemd::journal::Journal.open_folder() and .open(): the JournalFiles flags were consumed although not necessary. I adjusted it to borrow (&).

New Feature: "Serde". By default Serde is off. If the feature is activated, some enums & structs in systemd::journal are derived for serialization and deserialisation.

### CODE REVIEW

**Comment by ente76** [comment]
I replaced the try!() by the new ? and I removed one mut so the warnings on my project are more limited

**Comment by ente76** [comment]
#4cf4e57: cargo.toml added edition = "2018" --> all compilation errors fixed (a save change)
#be1cd18: mem::uninitialized is deprecated. The new replacement used instead. (a save change)
#664c92b: some clippy hints / warnings analysed & adjusted. Most of the stuff is boring (e.g. match bool). Some of the changes are raw pointer handling and may be worth a second check.

**Comment by jmesmon** [comment]
Hey @ente76 , thanks for working on this and sorry about taking a while to get back to you. I'd like to merge this PR. it looks like the build failure right now is just due to the `Cargo.lock` file being outdated. Could you bump it? (alternately, it might make sense to remove `Cargo.lock` from the repo and tweak the docker setup to allow writing one out).

**Comment by ente76** [comment]
I won't do such adjustment. Listen: I spent quite some time to provide as good as possible code. You did take more than 3 month and after that you are even too lazy to incorporate the code into the master? You request me to make adjustments? Lets be realistic: I did already adjust my infrastructure so I don't depend on you. My project will work on a local fork. All changes will be published / pushed onto your repository. Whether you incorporate it or not is none of my business anymore.

**Comment by jmesmon** [comment]
Thanks for your feed back.
The changes were largely incorporated into the 0.5.0 release (with `Copy` instead of using `&` for `JournalFiles`)

**Pull request closed without merging**
