### PR TITLE
method to get current cursor id and wrapper for 'sd_journal_get_realtime_usec'

### PR DESCRIPTION
**Pull request by kteza1**

### CODE REVIEW

**Comment by jmesmon** [comment]
Merged, thanks.

**Comment by kteza1** [comment]
In crates.io, this crate is versioned 0.0.8 whereas in repo it's 0.0.7. Is this a mistake? Also, could you please push these changes to crates.io?

**Comment by jmesmon** [comment]
I'm working through that at the moment. Apparently I was wrong about CString and allocations, so I'm fixing bits up there. Also switched get_realtime_us() to a `timestamp()` function that returns std::time::SystemTime (does that still work for your use case?).

Not sure why the version is funny.

**Comment by jmesmon** [comment]
I've made a new release on crates.io. I'll look into the strange versioning at some point (might have missed a few commits on one of my systems...)

**Comment by kteza1** [comment]
SystemTime is even better. Thanks :)

**Pull request merged**
