### PR TITLE
Introduce JournalEntry struct and refactor JournalRef to use it

### PR DESCRIPTION
**Pull request by dfreese**
This introduces a new struct, JournalEntry, which just wraps the
JournalRef and then provides an interface to all of the field specific
commands.  I didn't go so far as to deprecate the functionality that was
refactored out without feedback on the general idea of the structure.
This provided a little bit more of a hierarchy that I found easier to
reason about.

This does provide an Iterator implementation, which I made as it's own
struct `EntryIter`, to allow for a different `EntryUniqueIter` and
`EntryUniqueAvailableIter` later on.

I debated about the name of the `next_field` function.  The pattern for
function names in JournalEntry is typically just to remove the
`sd_journal_` and `_data` parts of the C API's function name.  This
would suggest `enumerate` be used.  I worried about that becoming
confusing with `journal.entry().iter().enumerate()`.  Happy to change
that, though, to remain consistent.

Since this is just a refactor, I didn't add any additional tests
currently. I assumed that the coverage on the old functionality (now
using the new functionality under the hood) was sufficient.

This change should be non-breaking, but let me know if I missed
something.

### CODE REVIEW

**Comment by dfreese** [comment]
Still generally like this idea, but I think the lifetimes associated with the iterator are incorrect.

**Comment by jmesmon** [comment]
Ya, I don't think we can use iterators for the sd_journal accessors here because of it's lifetime needs.

> The returned data is in a read-only memory map and is only valid until the next invocation of sd_journal_get_data(), sd_journal_enumerate_data(), sd_journal_enumerate_available_data(), or when the read pointer is altered. 

Basically, this means we need to have the lifetime taken by the borrow in `next()` attach to the returned item rather than the lifetime of the backing structure.

So rather than

```
pub struct EntryIter<'a, 'b> {
    entry: &'b mut JournalEntry<'a>,
}

impl<'a, 'b> Iterator for EntryIter<'a, 'b> {
    type Item = Result<JournalEntryField<'a>>;

    fn next(&mut self) -> Option<Result<JournalEntryField<'a>>> {
        self.entry.next_field().transpose()
    }
}
```

We'd need something like:

```
pub struct EntryIter<'a, 'b> {
    ...
}

impl<'a, 'b> NotReallyIterator for EntryIter<'a, 'b> {
    type Item = Result<JournalEntryField<'a>>;

    fn advance<'c>(&'c mut self) -> Option<Result<JournalEntryField<'c>>> {
        ...
    }
}
```
(untested, not validated, and I haven't looked at the other lifetimes)

I'm not sure if there's an existing pattern for this common in rust code, but I think it basically boils down to using `while let Some(v) = foo.advance()` loops instead of being able to use `for` loops directly.

I'm also not sure if there's a name here folks have converged on, or a common trait we might use.

All of these could definitely be interesting things to help clean up the journal reading API we have.

**Comment by jmesmon** [comment]
Also: agreed on trying to avoid using the name `enumerate()` as there's specific rust meaning that can confuse things.

**Comment by dfreese** [comment]
The consensus name appears to be [StreamingIterator](https://docs.rs/streaming-iterator/0.1.5/streaming_iterator/trait.StreamingIterator.html) based on the conversations [here](https://stackoverflow.com/questions/30422177/how-do-i-write-an-iterator-that-returns-references-to-itself) and [here](http://smallcultfollowing.com/babysteps/blog/2016/11/03/associated-type-constructors-part-2-family-traits/#introducing-type-families).

Allowing the std::iter::Iterator trait to behave in a streaming way appears to require [GAT](https://github.com/rust-lang/rust/issues/44265)s or Generic Associated Types, but a different, streaming iterator-like would be a way to do that in the meantime.  Not sure how you'd feel about introducing something like that or taking a dependency on something like `streaming-iterator`

**Comment by jmesmon** [comment]
Using streaming-iterator here seems fine to me. I'm open to using that crate to give the journal a more ergonomic api.

**Comment by dfreese** [comment]
Closing this for now as I'm not going to have a chance to get back around to it.

**Pull request closed without merging**
